# AI Agent Code Change - DEMO C (Cross-App Access)
# =======================================================
# Generated by : CodingAgent-Demo-C  (wlp144k6rrlQJjNQ5698)
# Acting for   : supradeep@idnty.one
# Granted scope: agent:codechange
# Timestamp    : 2026-06-14 11:42:28 UTC
# Flow         : User → Org AS (ID Token) → ID-JAG → Custom AS (scoped token) → GitHub
# =======================================================

def get_delegated_info():
    return {
        "agent": "CodingAgent-Demo-C",
        "user":  "supradeep@idnty.one",
        "scope": "agent:codechange",
        "timestamp": "2026-06-14 11:42:28 UTC",
        "note": "Committed via Okta Cross-App Access (XAA) token exchange flow."
    }
