# AI Agent Code Change
# Generated by: CodingAgent-Demo
# Authorised by: Okta AI-Agents-AuthServer
# Timestamp: 2026-05-23 15:08:14

def greet_user(name):
    return f"Hello, {name}! Access governed by Okta."
